config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :welcome
  root 'welcome#index'
  resources :camp_multi_steps
  namespace :admin do
    resources :users
    resources :camps
  end
  devise_for :users, controllers: {
    registrations: 'registration',
    sessions: 'sessions',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/navbar/navbar.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
    <!-- Container wrapper -->
	<div class="container-fluid">
		<!-- Collapsible wrapper -->
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<!-- Navbar brand -->
			<a class="navbar-brand" href="#">Camp Encounters</a>
			<!-- Left links -->
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<li class="nav-item">
					<%= link_to "Dashboard", root_path, class: "nav-link" %>
				</li>
				<li class="nav-item">
					<%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
				</li>
				<li class="nav-item">
					<%= link_to "User Panel", admin_users_path, class: "nav-link" %>
				</li>
        <li class="nav-item">
					<%= link_to "Camps Panel", admin_camps_path, class: "nav-link" %>
				</li>
			</ul>
			<!-- Left links -->
		</div>
		<!-- Collapsible wrapper -->

		<!-- Right elements -->
		<div class="d-flex align-items-end">
			<!-- Avatar -->
				<div class="btn-group dropstart">
					<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
						Account
					</button>
					<ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
						<li><button class="dropdown-item" type="button"><%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %></button></li>
						<li><button class="dropdown-item" type="button"><%= link_to "Sign Out", destroy_user_session_path, method: 'delete', class: "dropdown-item" %></button></li>
					</ul>
				</div>
			</div>
		</div>
		<!-- Right elements -->
	</div>
    <!-- Container wrapper -->
</nav>
<!-- Navbar -->