config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :welcome
  root 'welcome#index'
  resources :camp_multi_steps
  namespace :admin do
    resources :users
    resources :camps
  end
  devise_for :users, controllers: {
    registrations: 'registration',
    sessions: 'sessions',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/_form.html.erb
<%= form_for @user do |f| %>
    <%= f.label :first_name %><br/>
    <%= f.text_field :first_name %><br>
    <br>
    <%= f.label :last_name %><br/>
    <%= f.text_field :last_name %><br>
    <br>
    <%= f.label :phone_number %><br/>
    <%= f.text_field :phone_number %><br>
    <br>
    <%= f.label :country %><br/>
    <%= f.country_select :country , {} %><br>
    <br>
    <%= f.label :email %><br/>
    <%= f.email_field :email %><br>
    <br>

    <%= f.submit %>

<% end %>

app/views/admin/index.html.erb
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Users ID</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Phone Number</th>
      <th>Country</th>
      <th>Email</th>
      <th>Role</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
 <tbody>
  <% @users.each do |user|%>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.phone_number %></td>
      <td><%= user.country %></td>
      <td><%= user.email %></td>
      <td><%= user.type %></td>
      <td><%= link_to "View |", admin_path(user) %></td>
      <td><%= link_to "Edit |", edit_admin_path(user) %></td>
      <td><%= link_to "Delete ", admin_path(user), method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
  <%end%>
 </tbody>

</table>