config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :welcome
  root 'welcome#index'
  resources :camp_multi_steps
  namespace :admin do
    resources :users
    resources :camps
  end
  devise_for :users, controllers: {
    registrations: 'registration',
    sessions: 'sessions',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

require 'csv'
class User < ApplicationRecord
  has_one_attached :image

  def thumbnail
    image.variant(resize: '300x200!')
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  def self.to_csv
    attributes = %w[id first_name last_name email country phone_number]

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << attributes.map { |attr| user.send(attr) }
      end
    end
  end

  enum gender: { other: 0, male: 1, female: 2 }
  attribute :agreement, :integer
  validates :agreement, acceptance: { accept: 1 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable, :confirmable

  validates :phone_number, presence: true, numericality: true, length: { minimum: 10, maximum: 15 }
  validates :email, uniqueness: true, presence: { case_sensitive: false }
  validates :first_name, presence: true, length: { minimum: 2, maximum: 10 }
  validates :last_name, presence: true, length: { minimum: 2, maximum: 10 }
  validates :password, presence: true, confirmation: true,
                       format: {
                         with: /\A[a-zA-Z0-9. !@#$%^&*()_ -+=]+\Z/,
                         message: '(minimum 7 characters with at least one capital letter and a special character)',
                       }

  scope :simple_users, -> { where(type: nil) }
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < ApplicationController
  before_action :find_user, only: %i[show edit update destroy]
  helper_method :sort_column, :sort_direction

  def index
    if params[:search_key]
      @users = User.where('LOWER(first_name) LIKE ? OR LOWER(email) LIKE ? ',
      "%#{params[:search_key]}%", "%#{params[:search_key]}%").page(params[:page])
    else
      @users = User.order(sort_column + ' ' + sort_direction)
      @users = User.order(:id).page(params[:page])
      respond_to do |format|
        format.html
        format.csv { send_data @users.to_csv }
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.welcome_email(@user).deliver_now
      redirect_to admin_users_path, notice: 'User Successfully Created.'
    else
      render 'new', notice: 'Fields are missing.'
    end
  end

  def show
    if current_user.type? == 'Admin'
      render 'users#index'
    elsif current_user.type? == 'SuperAdmin'
      render 'users#index'
    else
      redirect_to root_path
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path
    else
      render 'edit', notice: 'User Successfully Updated.'
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :id, :first_name, :last_name, :email, :phone_number, :password, :country, :type, :image
    )
  end

  def sort_column
    params[:sort] || 'fname'
  end

  def sort_direction
    params[:direction] || 'asc'
  end
end

app/helpers/admin/user_helper.rb
# frozen_string_literal: true

module Admin::UserHelper
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<div class="container-fluid w-50 border rounded shadow mt-5 p-4 bg-light ">
  <div class = "text-center">
    <%= render 'profile' %>
  </div>
  <br>

  <%= form_for [:admin, @user] do |f| %>

  <div class="form-outline mb-4">
    <%= f.file_field :image %><br>
    <%= f.label :Upload_Image %><br/>
    <br>
  </div>
    
  <div class="row mb-4">
    
    <div class="col">
      <div class="form-outline" >
        <%= f.label :first_name %><br/>
        <%= f.text_field :first_name, autofocus: true, class: "form-control" %><br>
        <br>
      </div>
    </div>

    <div class="col">
      <div class="form-outline" >
        <%= f.label :last_name %><br/>
        <%= f.text_field :last_name, autofocus: true, class: "form-control" %><br>
        <br>
      </div>
    </div>

  </div>


    <div class="form-outline mb-4">
      <%= f.label :phone_number %><br/>
      <%= f.text_field :phone_number, autofocus: true, class: "form-control" %><br>
      <br>
    </div>

    <div class="form-outline mb-4">
      <%= f.label :country %><br/>
      <%= f.country_select :country , {}, class: "dropdown-item" %><br>
      <br>
    </div>

    <div class="form-outline mb-4">
      <%= f.label :email %><br/>
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %><br>
      <br>
    </div>

    <div class="form-outline mb-4">
      <%= f.label :password %><br/>
      <%= f.password_field :password, class: "form-control" %>
      <br>
    </div>

    <div class="text-center">
      <%= f.submit class: "btn btn-primary mb-4"%>
      <% end %>
    </div>
</div>

app/views/admin/users/_profile.html.erb
<% if @user.image.attached? %>
  <img src = "<%= (url_for(@user.image)) %>" style="width: 150px; height: 150px;" class="rounded-circle shadow-4" alt="username">
<% else %>
<%= image_tag "blank.png"%>
<% end %>

app/views/admin/users/edit.html.erb
<h1 class = "text-center">Edit Your Details</h1>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<div class="container-fluid w-75 border rounded shadow mt-5 p-4 ">
 <h1>Listing Users</h1>

  <table>
    <form action="<%= admin_users_path %>">
      <div class="row">
		
        <div class="col">
          <div class="input-group input-group-sm" style="width: 250px;">
            <input type="text" name="search_key">
            <button type="submit">Search</button>
          </div>
        </div>

        <div class="col">
          <div class="input-group input-group-sm" style="width: 250px; margin-left: 80%; ">
            <%= link_to "Add User", new_admin_user_path, class: "btn btn-success "%></td>
          </div>
          <div  class="input-group input-group-sm" style="width: 250px; margin-left:74%; " >
            <%= link_to "Export Users", admin_users_path(format: :csv), class: "btn btn-success mb-4" %>
          </div>
        </div>

      </div>
    </form>

    <thead>
      <tr>
        <th><%= sortable "User's ID" %></th>
        <th><%= sortable "First Name" %></th>
        <th><%= sortable "Last Name" %></th>
        <th><%= sortable "Phone Number" %></th>
        <th><%= sortable "Country" %></th>
        <th><%= sortable "Email" %></th>
        <th><%= sortable "Role" %></th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
 
    <tbody>
     <% @users.each do |user|%>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.phone_number %></td>
        <td><%= user.country %></td>
        <td><%= user.email %></td>
        <td><%= user.type %></td>
        <td><%= link_to "View |", admin_user_path(user) %></td>
        <td><%= link_to "Edit |", edit_admin_user_path(user) %></td>
        <td><%= link_to "Delete ", admin_user_path(user) , method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
     <%end%>
   </tbody>

  </table>
    <%= paginate @users%>
</div>

app/views/admin/users/new.html.erb
<h1 class= "text-center">Enter Your Details</h1>

<%= render 'form' %>

app/views/admin/users/show.html.erb
<div class="container-fluid w-25 border rounded shadow mt-5 p-4 text-center">  
  <%= render 'profile' %>
  <%= image_tag (@user.thumbnail) if @user.image.attached? <%>
    <p><b>First Name: </b><%= @user.first_name %></p>
    <p><b>Last Name: </b><%= @user.last_name %></p>
    <p><b>Email: </b><%= @user.email %></p>
    <p><b>Phone Number: </b><%= @user.phone_number %></p>
    <p><b>Country: </b><%= @user.country %></p>
    <br>
  <%= link_to 'Edit User', edit_admin_user_path(@user) %>
  <br>
  <%= link_to 'Delete User', admin_user_path(@user), method: :delete, data: { confirm: "Are you sure?" } %>
</div>