config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :welcome
  root 'welcome#index'
  resources :camp_multi_steps
  namespace :admin do
    resources :users
    resources :camps
  end
  devise_for :users, controllers: {
    registrations: 'registration',
    sessions: 'sessions',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/camp.rb
# frozen_string_literal: true

require 'csv'
class Camp < ApplicationRecord
  enum camp_type: { Virtual: 0, Physical: 1, Hybrid: 2 }
  enum camp_status: { Inactive: 0, Active: 1 }

  def self.to_csv
    attributes = %w[id title locations camp_status applicant_registration_start_date]

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |camp|
        csv << attributes.map { |attr| camp.send(attr) }
      end
    end
  end
end

app/controllers/admin/camps_controller.rb
# frozen_string_literal: true

#
# Missing top-level documentation
#

class Admin::CampsController < ApplicationController
  before_action :find_camp, only: %i[show edit update destroy status_update]
  helper_method :sort_column, :sort_direction

  def index
    if params[:search_key]
      @camps = Camp.where(
        'LOWER(title) LIKE ?',
        "%#{params[:search_key]}%",
      ).page(params[:page])
    else
      @camps = Camp.order(sort_column + ' ' + sort_direction)
      @camps = Camp.order(:id).page(params[:page])
      respond_to do |format|
        format.html
        format.csv { send_data @camps.to_csv }
      end
    end
  end

  def new
    @camp = Camp.new
  end

  def create
    @camp = Camp.new(camp_params)
    if @camp.save
      redirect_to admin_camps_path, notice: 'Camp Successfully Created.'
    else
      render 'new', notice: 'Fields are missing.'
    end
  end

  def show; end

  def edit; end

  def update
    if @camp.update(camp_params)
      redirect_to admin_camp_path
    else
      render 'edit', notice: 'Camp Successfully Updated.'
    end
  end

  def destroy
    @camp.destroy
    redirect_to admin_camps_path
  end

  def status_update
    @camp.update(status: params[:status])
    @camps = Camp.all
  end

  private

  def find_camp
    @camp = Camp.find(params[:id])
  end

  def camp_params
    params.require(:camp).permit(
      :id, :title, :camp_type, :camp_status, :applicant_registration_start_date,
      :applicant_registration_start_time, :applicant_registration_end_date,
      :applicant_registration_end_time, :parent_application_start_date,
      :parent_application_start_time, :parent_application_end_date,
      :parent_application_end_time, locations: []
    )
  end

  def sort_column
    params[:sort] || 'title'
  end

  def sort_direction
    params[:direction] || 'asc'
  end
end

app/helpers/admin/camps_helper.rb
# frozen_string_literal: true

module Admin::CampsHelper
end

app/views/admin/camps/_form.html.erb
<div class="container-fluid w-50 border rounded shadow mt-5 p-4 ">
 <%= form_for [:admin, @camp] do |f| %>
    <div class="row mb-4">
      <div class="col">
        <div class="form-outline" >
          <%= f.label :Camp_title %><br/>
          <%= f.text_field :title %><br>
          <br>
        </div>
      </div>
      <div class="col">
        <div class="form-outline">
          <%= f.label :Camp_type %><br/>
          <%= f.select :camp_type, Camp.camp_types.keys,{}, class: "form-select" %><br>
          <br>
        </div>
      </div>
      <div class="col">
        <div class="form-outline">
          <%= f.label :Camp_status %><br/>
          <%= f.select :camp_status, Camp.camp_statuses.keys,{}, class: "form-select" %><br>
          <br>
        </div>
      </div>
    </div>

<% locations = ['Kenya', 'India', 'Pakistan', 'Expedition Kenya', 'Expedition India']%>
  <% locations.each do |location|%>
    <div class="btn-group mb-3" role="group" aria-label="Basic checkbox toggle button group">
      <%= f.label location %>
      <%= f.check_box :locations, { multiple: true }, location , false %><br>
    </div>
    <br>
  <% end %>

<div class = "row">
  <div class = "col form-outline mb-4">
   <%= f.label :applicant_registration_start %><br/>
   <%= f.text_field :applicant_registration_start_date, type: :date, class: "form-control" %>
   <%= f.text_field :applicant_registration_start_time, type: :time, class: "form-control" %>  
  <div>

  <div class = "col form-outline mb-4">
   <%= f.label :applicant_registration_end %><br/>
   <%= f.text_field :applicant_registration_end_date, type: :date, class: "form-control" %>
   <%= f.text_field :applicant_registration_end_time, type: :time, class: "form-control" %>  
  <div>
</div>

  <div class = "row">
    <div class = "col form-outline mb-4">
     <%= f.label :parent_registration_start %><br/>
     <%= f.text_field :parent_application_start_date, type: :date, class: "form-control" %>
     <%= f.text_field :parent_application_start_time, type: :time, class: "form-control" %>  
    <div>

    <div class = "col form-outline mb-4">
     <%= f.label :parent_registration_end %><br/>
     <%= f.text_field :parent_application_end_date, type: :date, class: "form-control" %>
     <%= f.text_field :parent_application_end_time, type: :time, class: "form-control" %>  
    <div>

  </div>

  <div class="text-center">
    <%= f.submit class: "btn btn-primary mb-4" %>
    <% end %>
  </div>
</div>

app/views/admin/camps/edit.html.erb
<h1 class = "text-center">Camp Settings</h1>

<%= render 'form' %>

app/views/admin/camps/index.html.erb
<div class="container-fluid w-75 border rounded shadow mt-5 p-4 ">
 <h1>Listing Camps</h1>
  
  <table>
    <form action="<%= admin_camps_path %>">
      <div class="row">
        <div class="col">
          <div class="input-group input-group-sm" style="width: 250px;">
            <input type="text" name="search_key">
            <button type="submit">Search</button>
          </div>
        </div>
        <div class="col">
          <div class="input-group input-group-sm" style="width: 250px; margin-left: 80%; ">
            <%= link_to "Add Camp", new_admin_camp_path, class: "btn btn-success " %></td>
          </div>
          <div  class="input-group input-group-sm" style="width: 250px; margin-left: 74%; ">
            <%= link_to "Export Report", admin_camps_path(format: :csv), class: "btn btn-success mb-4" %>
         </div>
        </div>
     </div>
   </form>
   <thead>
      <tr>
        <th><%=sortable "Camp's ID" %></th>
        <th><%=sortable "Title" %></th>
        <th><%=sortable "Camp Locations" %></th>
        <th><%=sortable "Status" %></th>
        <th><%=sortable "Registration Date" %></th>
        <th colspan="3">Actions</th>
      </tr>
   </thead>
     
   <tbody>
     <% @camps.each do |camp|%>
     <tr>
        <td><%= camp.id %></td>
        <td><%= camp.title %></td>
        <td><%= camp.locations %></td>
        <td><%= camp.camp_status %></td>
        <td><%= camp.applicant_registration_start_date %></td>
        <td><%= link_to "View |", admin_camp_path(camp) %></td>
        <td><%= link_to "Edit |", edit_admin_camp_path(camp) %></td>
        <td><%= link_to "Delete ", admin_camp_path(camp) , method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
      <%end%>
   </tbody>
  </table>
  <%= paginate @camps %>
</div>

app/views/admin/camps/new.html.erb
<h1 class = "text-center">Camp Form</h1>

<%= render 'form' %>

app/views/admin/camps/show.html.erb
<div class="container-fluid w-25 border rounded shadow mt-5 p-4">  
  <h4>Camp: <%=@camp.id%><h4>
  <p><b>Camp Title: </b><%= @camp.title %><p>
  <p><b>Camp Type: </b><%= @camp.camp_type %></p>
  <p><b>Locations: </b><%= @camp.locations %></p>
  <p><b>Status: </b><%= @camp.camp_status %></p>
  <p><b>Applicant Registration Start Date: </b><%= @camp.applicant_registration_start_date %></p>
  <p><b>Applicant Registration Start Time: </b><%= @camp.applicant_registration_start_time %></p>
  <p><b>Applicant Registration End Date: </b><%= @camp.applicant_registration_end_date %></p>
  <p><b>Applicant Registration End Time: </b><%= @camp.applicant_registration_end_time %></p>
  <p><b>Parent Application Start Date: </b><%= @camp.parent_application_start_date %></p>
  <p><b>Parent Application Start Time: </b><%= @camp.parent_application_start_time %></p>
  <p><b>Parent Application End Date: </b><%= @camp.parent_application_end_date %></p>
  <p><b>Parent Application End Time: </b><%= @camp.parent_application_end_time %></p>

</div>